on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

name: ci

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.6/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
          echo | source $HOME/.profile && $HOME/.elan/bin/elan --version

      - uses: actions/checkout@v2

      - name: build GroupComp
        run: |
          lake exe cache get
          lake build
